version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: mod

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocritic

  disable:
    - prealloc
    - gosec
    - unparam

  settings:
    errcheck:
      check-blank: true

    misspell:
      locale: US

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - commentFormatting
        - hugeParam
  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
      # Run some linter only for test files by excluding its issues for everything else.
      - path-except: _test\.go
        linters:
          - forbidigo
formatters:
  enable:
    - goimports
issues:
  max-same-issues: 5
  max-issues-per-linter: 50

