
# kubectl create deployment consumer --image=sim/nats/consumer:1.0 --replicas=1  --dry-run=client -oyaml>consumer.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: msggw
  name: msggw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msggw
  strategy: {}
  template:
    metadata:
      labels:
        app: msggw
    spec:
      containers:
      - image: msggw:1.0.0
        imagePullPolicy: IfNotPresent
        name: msggw
        volumeMounts:
        - name: config-volume
          mountPath: /app/configs/config.json
          subPath: config.json
        resources: {}
      volumes:
      - name: config-volume
        configMap:
          name: msggw-config
